### ISSUE TITLE
Go package names shouldn't be same color as the variable names

### ISSUE THREAD

**Issue by enkeyz** [dannymcgee/vscode-go-syntax#4]
![image](https://user-images.githubusercontent.com/17646853/129563014-fdf4c8b2-d803-4097-8966-ffc2900cd115.png)

**Comment by dannymcgee** [comment]
Thanks for the report @enkeyz. This is a long-standing issue -- unfortunately this is beyond the capabilities of a TextMate grammar, which is just a stateless line-by-line Regex scanner. Semantic tokens would be the way to provide this kind of information, but I don't believe there's a way for me to do that here without overriding the main Go extension (which obviously provides a lot more useful intelligence that you wouldn't want to lose just for the sake of highlighting).

You might want to try turning on semantic tokens in the settings for the main Go extension, and if that doesn't yield good results, posting an issue to that repo so that they're aware of the problem. In the meantime I'll keep this open so that folks are aware of the limitation.

**Comment by dannymcgee** [comment]
I guess I should also mention that it would be totally feasible to add a rule that matches the names of standard-library packages and highlights them as packages. I had an early draft that did that, but since they're not reserved keywords, it would be possible to have an ordinary variable be incorrectly colored as a package just because it happened to be named `fmt` (for example). So I eventually decided that it would be better to err on the side of too general than too specific.
